version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17-browsers
    
    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: Docker version
          command: pwd
      
workflows:
  build_docker_image:
    jobs:
      - build
