version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.24-buster-browsers
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update --allow-releaseinfo-change
            sudo apt-get install -y docker.io
      - run:
          name: Docker version
          command: docker version
      - run:
          name: Start docker engine
          command: sudo systemctl start docker
      - run:
          name: Build Docker Image
          command: |
            TAG=2.6.20
            docker build -t myapp-image:$TAG .

workflows:
  build_docker_image:
    jobs:
      - build
