version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17-browsers

    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: docker version
          command: sudo docker info
      - run:
          name: Build Docker image
          command: docker build -t react-app:1 .

workflows:
  build_and_test:
    jobs:
      - build
