version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run:
          name: Docker version
          command: docker version
      # - run:
      #     name: Build Docker Image
      #     command: |
      #       TAG=2.6.20
      #       docker build -t myapp-image:$TAG .

workflows:
  build_docker_image:
    jobs:
      - build
