version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=latest
          docker build -t sangukou/react-app:$TAG .
          echo $DOCKER_PAT | docker login -u $DOCKER_USER --password-stdin
          docker push sangukou/react-app:$TAG