version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=latest
          docker build -t react-app:$TAG .
          # echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          # docker push CircleCI-Public/circleci-demo-docker:$TAG