version: 2.1

jobs:
  build:
    docker:
      - image: node:10.19.0-alpine3.11
    steps:
      - checkout
      - run:
          TAG = 2.6.20
          name: Build Docker Image
          command: |
            docker build -t myapp-image:$TAG .

workflows:
  build_docker_image:
    jobs:
      - build
  