version: 2

jobs:
  build_test:
    docker:
      - image: node:10.19.0-alpine3.11

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker build -t myapp-image .

      # - run:
      #     name: Run Docker Container
      #     command: |
      #       docker run -d --name myapp-container -p 3000:3000 myapp-image

      # - run:
      #     name: Run Tests
      #     command: |
      #       docker exec -it myapp-container npm test