# version: 2.1

# jobs:
#   build:
#     docker:
#       - image: cimg/node:14.17-browsers
#     steps:
#       - checkout
#       # ... steps for building/testing app ...

#       - setup_remote_docker:
#           docker_layer_caching: true

#       # build and push Docker image
#       - run: |
#           TAG=latest
#           docker build -t sangukou/react-app:$TAG .
#       - run: |
#           name: Run App Container
#           command: |
#             docker run -d -p 80:3000 --name react-app sangukou/react-app:$TAG npm start
# echo $DOCKER_PAT | docker login -u $DOCKER_USER --password-stdin
# docker push sangukou/react-app:$TAG

version: 2.1
orbs:
  slack: circleci/slack@4.12.6

executors:
  ubuntu-22-04:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true


            
jobs:
  prepare-server:
    docker:
      - image: sangukou/react-app:latest
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD


    steps:
      - run: |
           docker build -t sangukou/react-app:latest .
  
  start-tests:
    docker:
      - image: sangukou/my-cypress:latest
    steps:
      - run: |
           docker build -t sangukou/my-cypress:latest .

  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: C06GH4Z8ACT
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*test results*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }

workflows:
  uat:
    jobs:
      -  prepare-server:
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - test
      - start-tests:
          requires:
            - prepare-server
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - test
      - notify:
          context: slackNotif
          requires:
            - start-tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - test