version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17-browsers

    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run:
          name: docker version
          command: sudo docker info
      - run:
          name: Build Docker image
          command: docker build -t react-app:1 .

workflows:
  build_and_test:
    jobs:
      - build
