version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.24-buster-browsers
    steps:
      - checkout
      - run:
          name: Start Docker Service
          command: |
            sudo service docker start
      - run:
          name: Build Docker Image
          command: |
            TAG=2.6.20
            docker build -t myapp-image:$TAG .

workflows:
  build_docker_image:
    jobs:
      - build